name: C/C++ CI

on:
  push:
    branches: [ mod ]
#   pull_request:
#     branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install packages
      run: sudo apt-get install autoconf automake libtool curl make g++ unzip
    - name: build
      run: |
        ./autogen.sh && \
        ./configure --prefix=$PWD/dist && \
        make && \
        make check && \
        make install
